dict1:
    a: A
    b: B
    c: C

dict2: {x: 1, y: 2, z: 3}

list1:
    - A
    - B
    - C

list2: [1, 2, 3]

list_of_dict:
    -
        id: 1
        name: A
    -
        id: 2
        name: B

# 布尔值
boolean:
    - True  # true, TRUE 都可以
    - true
    - TRUE
    - False  # false, FALSE 都可以
    - false
    - FALSE


# 整型
int: 123

# 浮点数
float:
    - 3.14
    - 1.e-5  # 可以使用科学记数法

string:
    - abc
    - Hello World
    - Hello "Python"  # 单引号、双引号都可以
    - "I'm xxx"

a: &a
    x: 1
    y: 2

m:
    n: 3
    <<: *a

t:
  - &showell Steve
  - Clark
  - Brian
  - Oren
  - *showell